<div class="row">
  <div class="col-md">
    <h3>Remove Duplicate Books</h3>
    <small>A duplicate book is where 2 product posts share the same ISBN and Title</small><br/>
    <small>All duplicate books are moved to the Trash where they can be permanently
      deleted or restored if desired
    </small>
    <br/><br/>
    <form action="<?php echo admin_url('admin-post.php')?>" method="post"
          name="export_books">
      <input type="hidden" name="action" value="export_books" />
      <input type="submit" name="export_books_csv_submit" value="Export Books to CSV" />
      <!--<input type="submit" name="export_books_json_submit" value="Export Books to JSON" />-->
    </form>
  </div>
</div>
